### ISSUE TITLE
how do you register your bugsnag API key

### ISSUE THREAD

**Issue by austenLacy** [marnusw/bunyan-bugsnag#1]
how do you register your bugsnag API key?

**Comment by marnusw** [comment]
Since the Bugsnag library is imported as a Singleton you can initialize it separately:

```javascript
import bugsnag from 'bugsnag'
bugsnag.register(BUGSNAG_API_KEY)

// Carry on with the Bunyan setup
```

There may be other Bugsnag config you'd want to do based on the [docs](https://docs.bugsnag.com/platforms/nodejs/express/configuration-options/).

In the project I created this library for all the various services are configured separately, so I never considered this. It would make sense to allow passing the Bugsnag config as part of the `options` for this library though. I'll work that up and release an update in the near future.

**Comment by kinson** [comment]
@marnusw I don't see this in the package right now, mind if I create a pr to pass the bugsnag config as an option? Or would it be better to pass the bugsnag object entirely as I am currently setting it up in a separate file and then exporting it.

**Comment by marnusw** [comment]
A PR is welcome. I can't recall if the Node Bugsnag client is created with
´new´ or used as a global which is just configured. If the former I'd
prefer passing the instance in, if not the configuration object can be
passed in.

I think it's the latter, though, which is why it also works just fine to
configure Bugsnag elsewhere and then just use the banyan stream where you
set up logging.

Passing in options should be optional so it stays backwards compatible.

**Comment by kinson** [comment]
From my observations the Bugsnag client is not a singleton. I have attempted to register it and then call the bugsnagStream() function and it is not sending errors.

I will open a pr shortly to support passing in a bugsnag instance.

**Comment by kinson** [comment]
If you have any available time to review the open pr I would greatly appreciate it!

**Comment by marnusw** [comment]
For convenience the `bugsnagApiKey` option is now supported and will be registered on the `bugsnag` client if provided. If more complex Bugsnag configuration is required handle that separately and leave this stream to pick it up when it imports the Bugsnag Node.js client.
